getEmergencyNotice:
  call: http.post
  args:
    url: "[#CHATBOT_RESQL]/backoffice/get-emergency-notice"
  result: getEmergencyNoticeResult

validateEmergencyNoticeExists:
  switch:
    - condition: "${getEmergencyNoticeResult.response.body.length > 0}"
      next: mapEmergencyNoticeData
  next: return_not_found

mapEmergencyNoticeData:
  call: http.post
  args:
    url: "[#CHATBOT_DMAPPER]/backoffice/hbs/return_emergency_notice"
    headers:
      type: json
    body:
      configurationArray: ${getEmergencyNoticeResult.response.body}
  result: formattedData

return_result:
  return: ${formattedData.response.body}
  next: end

return_not_found:
  return: "error: not found"
