loadTrainedModel:
  call: http.post
  args:
    url: "[#CRON_INSTANCE]/execute/load_trained_model/load_trained_model_now?versionNumber=${incoming.body.versionNumber}"
  next: returnSuccess

returnSuccess:
  return: "Model copied and loaded successfully"
  wrapper: false
  next: end
